/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package timeline;

import javax.swing.JLabel;

/**
 *
 * @author Bhuvaneshwar
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subject = new javax.swing.JLabel();
        bodycontent = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subject.setText("Sample Text");
        subject.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectMouseClicked(evt);
            }
        });
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 320, 94));

        bodycontent.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare viverra pharetra. Duis fermentum nisl nec urna bibendum pellentesque. Vestibulum eleifend vehicula dignissim. In egestas ipsum tincidunt nulla hendrerit suscipit vitae a leo. Ut sollicitudin, nisi gravida pellentesque ullamcorper, quam orci vestibulum erat, non bibendum arcu est vel enim. Phasellus eget vulputate orci. Vivamus in velit sit amet nisi pharetra luctus.  Vivamus viverra pharetra augue, vel hendrerit dui tincidunt sed. Nam dictum sapien eu tempus commodo. Proin eu nunc ut purus aliquet pretium. Sed fermentum commodo tortor. Quisque sed nisl sit amet nunc euismod rhoncus at at ex. Pellentesque mollis felis ac nisl sollicitudin semper. Nam vel dui urna. Etiam lorem sem, elementum eu dui sit amet, dictum imperdiet ante. Aenean vitae elit dictum, dapibus nibh id, porttitor neque. Sed a pellentesque libero. Fusce sed magna sollicitudin, pellentesque elit ac, mattis purus. Vestibulum consequat rutrum libero, id pellentesque leo laoreet euismod. Vivamus euismod, lectus a condimentum finibus, quam lorem ultricies lorem, a suscipit nulla nisl at nibh.");
        jPanel1.add(bodycontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 24, 310, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 0, -1, 401));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectMouseClicked
//        for (int i = 0; i <10; i++) {
//            javax.swing.JLabel n=new JLabel();
//            jPanel1.add(n);
//        }
        TextArea.setText(new String(bodycontent.getText()));
    }//GEN-LAST:event_subjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel bodycontent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel subject;
    // End of variables declaration//GEN-END:variables
}
